const ICONS = [
    //overallcategory, subcategory, icon
    ['dessert', 'bakery', 'bread'],
    ['dessert', 'candy & chocolate', 'candy'],
    ['dessert', 'dessert bar', 'patisserie'],
    ['dessert', 'ice cream', 'icecream'],
    ['groceries', 'beer shop', 'beer'],
    ['groceries', 'cheese shop', 'cheese'],
    ['groceries', 'deli ', 'deli'],
    ['groceries', 'organic', 'farmstand'],
    ['groceries', 'specialty market', 'conveniencestore'],
    ['groceries', 'spice shop', 'pepper'],
    ['health', 'custom perfume', 'perfumery'],
    ['health', 'dental', 'drogerie'],
    ['health', 'fitness', 'fitness'],
    ['health', 'martial arts', 'karate'],
    ['health', 'medical', 'drugstore'],
    ['health', 'natural & alternative', 'rice'],
    ['health', 'pharmacy', 'drugstore'],
    ['health', 'pilates', 'yoga'],
    ['health', 'yoga', 'yoga'],
    ['laundromat', 'laundromat', 'laundromat'],
    ['restaurants', 'american', 'food'],
    ['restaurants', 'asian', 'food'],
    ['restaurants', 'austrailian', 'food'],
    ['restaurants', 'bar', 'bar_coktail'],
    ['restaurants', 'bbq', 'bbq'],
    ['restaurants', 'brazilian', 'food'],
    ['restaurants', 'broth', 'food'],
    ['restaurants', 'bubble tea', 'tea'],
    ['restaurants', 'cafe', 'cafe'],
    ['restaurants', 'chinese', 'food'],
    ['restaurants', 'cuban', 'food'],
    ['restaurants', 'domenican', 'food'],
    ['restaurants', 'ethiopian', 'food'],
    ['restaurants', 'french', 'food'],
    ['restaurants', 'georgian', 'food'],
    ['restaurants', 'greek', 'food'],
    ['restaurants', 'hookah bar', 'food'],
    ['restaurants', 'indian', 'food'],
    ['restaurants', 'irish', 'food'],
    ['restaurants', 'italian', 'food'],
    ['restaurants', 'japanese', 'food'],
    ['restaurants', 'jewish', 'food'],
    ['restaurants', 'juice bar', 'juice'],
    ['restaurants', 'korean', 'food'],
    ['restaurants', 'kosher', 'food'],
    ['restaurants', 'mediterranean', 'food'],
    ['restaurants', 'mexican', 'food'],
    ['restaurants', 'middle eastern', 'food'],
    ['restaurants', 'pizza', 'pizzaria'],
    ['restaurants', 'puerto rican', 'food'],
    ['restaurants', 'sandwich', 'sandwich'],
    ['restaurants', 'serbian', 'food'],
    ['restaurants', 'sushi', 'food'],
    ['restaurants', 'taiwanese', 'food'],
    ['restaurants', 'tapas', 'food'],
    ['restaurants', 'tea shop', 'tea'],
    ['restaurants', 'thai', 'food'],
    ['restaurants', 'ukrainian', 'food'],
    ['restaurants', 'vegan', 'vegetarian'],
    ['restaurants', 'vietnamese', 'food'],
    ['restaurants', 'wings', 'food'],
    ['retail', 'books', 'book'],
    ['retail', 'childrens', 'kids'],
    ['retail', 'fashion', 'clothing'],
    ['retail', 'gifts', 'gifts'],
    ['retail', 'vintage', 'clothing'],
    ['shops & services', 'appliances', 'coldstorage'],
    ['shops & services', 'beer shop', 'beershop'],
    ['shops & services', 'bicycle shop', 'bicycle_shop'],
    ['shops & services', 'composting', 'compost'],
    ['shops & services', 'dollar store', 'dollar'],
    ['shops & services', 'copies', 'printer'],
    ['shops & services', 'furnishing & building materials', 'tools'],
    ['shops & services', 'hardware', 'tools'],
    ['shops & services', 'locksmith', 'lock'],
    ['shops & services', 'pet supplies and grooming', 'pets'],
    ['shops & services', 'sake shop', 'sake'],
    ['shops & services', 'shipping', 'truck'],
    ['shops & services', 'stationery', 'pens'],
    ['shops & services', 'veterinary services', 'vet'],
    ['shops & services', 'wine shop', 'wine'],
    ['shops & services', 'yarn shop', 'textiles'],
    ['shops & services', 'hair', 'hair'],
    ['shops & services', 'florist', 'flowers'],
    ['shops & services', 'dive shop', 'snorkeling'],
    ['shops & services', 'sewing machine repair', 'tailor'],
    ['shops & services', 'computer & phone repair', 'phones']
]

export default ICONS;